version: '3.7'

services:
  bartosz-lauks-master-degree-mysql:
    container_name: bartosz-lauks-master-degree-mysql-dev
    ports:
      - '33063:3306'

  bartosz-lauks-master-degree-php:
    container_name: bartosz-lauks-master-degree-php-dev
    environment:
      APP_ENV: dev
      APP_VERSION: dev
      DATABASE_URL: mysql://root:@bartosz-lauks-master-degree-mysql:3306/bartosz-lauks-master-degree_dev

  bartosz-lauks-master-degree-nginx:
    container_name: bartosz-lauks-master-degree-nginx-dev
    ports:
      - '8083:80'

  bartosz-lauks-master-degree-rabbitmq:
    container_name: bartosz-lauks-master-degree-rabbitmq-dev
    ports:
      - '5672:5672'
      - '15672:15672'