version: '3.7'

services:
  bartosz-lauks-master-degree-mysql:
    container_name: bartosz-lauks-master-degree-mysql-prod
    ports:
      - '33061:3306'

  bartosz-lauks-master-degree-php:
    container_name: bartosz-lauks-master-degree-php-prod
    environment:
      APP_ENV: prod
      APP_VERSION: prod
      DATABASE_URL: mysql://root:@bartosz-lauks-master-degree-mysql:3306/bartosz-lauks-master-degree_prod

  bartosz-lauks-master-degree-nginx:
    container_name: bartosz-lauks-master-degree-nginx-prod
    ports:
      - '8081:80'

  bartosz-lauks-master-degree-rabbitmq:
    container_name: bartosz-lauks-master-degree-rabbitmq-prod
    ports:
      - '5672:5672'
      - '15672:15672'
